
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::163885031330:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-xsJyMoAGTQ74
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::163885031330:user/suresh
      username: suresh
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::163885031330:user/ramesh
      username: ramesh
    # - groups:
    #   - roboshop-trainee
    #   userarn: arn:aws:iam::160885265516:user/john
    #   username: john
    # - groups:
    #   - roboshop-trainee
    #   userarn: arn:aws:iam::160885265516:user/rahim
    #   username: rahim
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-13T00:22:32Z"
  name: aws-auth
  namespace: kube-system
  uid: 274dde7d-affa-4258-9575-67ce578142ff